# LLM Configuration
llm:
  provider: "openai"
  model: "gpt-4.1"
  temperature: 0.2

# Legacy settings (deprecated)
llm_model: "llama3.1:8b"
use_openai: false

# Application settings
docs_path: "docs"
top_k: 2
score_threshold: 0.5
