# LLM Configuration
llm:
  provider: "openai"
  model: "gpt-4.1"
  temperature: 0.2
  api_key_env: "OPENAI_API_KEY"

# Legacy settings (deprecated)
llm_model: "llama3.1:8b"
use_openai: false
openai_api_key: ""

# Application settings
docs_path: "docs"
top_k: 2
score_threshold: 0.5
