name: Test and Lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/base.txt -r requirements/dev.txt -e .

      - name: Run tests with pytest
        run: pytest

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
