name: Test and Lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests with pytest
        run: uv run pytest

      - name: Run pre-commit
        run: uv run pre-commit run --all
